apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: syfter-api-policy
  namespace: syfter
spec:
  podSelector:
    matchLabels:
      app: syfter-api
  policyTypes:
    - Ingress
  ingress:
    # Allow traffic from OpenShift router (ingress)
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
      ports:
        - protocol: TCP
          port: 4443
        - protocol: TCP
          port: 8000
