apiVersion: v1
kind: ConfigMap
metadata:
  name: syfter-pg-tuning
  namespace: syfter
data:
  tuning.conf: |
    max_wal_size = 4GB
    shared_buffers = 512MB
    work_mem = 256MB
    effective_cache_size = 1GB
    maintenance_work_mem = 256MB
    checkpoint_completion_target = 0.9
